COMPANIES = [
    "1st Advantage Federal Credit Union",
    "Altice",
    "Alya S.r.l.",
    "ARI Network Services 2, Inc",
    "AS \"Augstspriegumu Tikls\"",
    "Azteca",
    "Bat Blue",
    "Be Able s.r.l.",
    "Bell Integration",
    "BETAMONT s.r.o.",
    "BGH Tech Partner",
    "Bitbrains IT Services",
    "Blue Bridge Bond, UAB",
    "Bodybuilding.com",
    "BookingLive",
    "Bupa",
    "Caja Piura",
    "Cavnet",
    "CenterPoint Energy, Inc.",
    "China Net Cloud",
    "Citadele Bank",
    "City of Mesa",
    "Claro (Ecuador)",
    "Claro (Peru)",
    "Codefortytwo software",
    "Comfama",
    "Comindware Inc.",
    "CommuniG8 Limited",
    "Comtech Solacom Technologies Inc.",
    "Conexon, LLC",
    "Connecture",
    "Curium Pharma",
    "D1",
    "Dataprev",
    "Dublin City University",
    "DEAC",
    "Dell",
    "Deveryware",
    "Diplomat Holdings Ltd",
    "Israel Discount Bank, Ltd.",
    "Government of Australia Department of Infrastructure and Transport",
    "Docaposte",
    "Hutchison Drei Austria GmbH",
    "Destiny (NV)",
    "East Allen County Schools",
    "EDUBERN",
    "Eltele AS",
    "European Space Agency",
    "Execon",
    "Fellowtech",
    "Fichtner IT Consulting AG",
    "Focus IT Mexico",
    "Fraunhofer Institute for Production Technology IPT",
    "fTLD Registry Services, LLC",
    "GAPSA",
    "GlobeNet",
    "Globo",
    "Group Health Cooperative",
    "Harris Teeter Supermarkets, LLC",
    "ICC Networking",
    "IHI Terrasun Solutions",
    "ITBN Business Network GmbH",
    "ITtelligent Consulting Services",
    "IVPN Limited",
    "Kambi",
    "Lab9 Pro",
    "Linx",
    "Makonix SIA",
    "Mibanco",
    "Midco",
    "Navisite, LLC",
    "NATO Communications and Information Agency",
    "Neptuno",
    "Netia",
    "Netwatch",
    "Nexon",
    "Nextlink Internet",
    "NextNav",
    "NFOrce Entertainment B.V.",
    "NOS",
    "NTT Com Solutions",
    "NTT DATA Business Solutions AG",
    "Nucleus",
    "Vlaamse Overheid Departement Omgeving",
    "OnMobile Global Ltd.",
    "oXya",
    "Parallels, Inc",
    "PawBoost",
    "Petrobras",
    "The New Zealand Institute for Plant and Food Research Ltd.",
    "SBS Proactive, LLC",
    "Procergs",
    "Quickline Communications Limited",
    "Lojas Renner SA",
    "Riga Technical University",
    "RWE Renewables GmbH",
    "RxBenefits, Inc.",
    "Societe des Alcools du Quebec",
    "Savvii - Managed WordPress Hosting",
    "South Carolina Department of Natural Resources",
    "SEAT S.A.",
    "SEB Bank",
    "Seguros Bolivar",
    "Serpro",
    "Servnet",
    "San Francisco Department of Technology",
    "Sitesi",
    "Spencer Gifts LLC",
    "Sportium",
    "Sykehuspartner",
    "Telefonica Colombia",
    "Telent Technology Services Limited",
    "Telerik",
    "TigerLogic Corporation",
    "Water Authority",
    "Trayport Ltd.",
    "Total Server Solutions",
    "T-Systems Enterprise Services GmbH",
    "T-Systems P.R. China Ltd",
    "T-Systems (Mexico)",
    "VID (The State Revenue Service of Latvia)",
    "VIP Internet",
    "Vodacom",
    "VSAA (The State Social Insurance Agency)",
    "Wave Telecom",
    "WOM",
    "XS4ALL Internet bv",
    "Aswat Telecom & Media",
]
